### ISSUE TITLE
Documentação de uso

### ISSUE THREAD

**Issue by melyssamariana** [antonio-emilio/projeto_ed1#4]
Como o projeto utiliza conceitos de chave estrangeira e afins, é necessário criar-se um registro primeiramente para só depois fazermos alguma relação com ele.
Logo, para adicionar componentes a um projeto, seguiremos estes passos:

- Cadastrar um projeto;
- Cadastrar os componentes necessários;
- Criar a associação de projetos e componentes.

**Comment by antonio-emilio** [comment]
A interface foi desenvolvida de forma a ser intuitiva ao uso. Os conceitos mais importantes são:
Se você usará um componente em um determinado projeto, primeiramente você precisará cadastrá-lo.
