### ISSUE TITLE
Avaliação do Trabalho Final

### ISSUE THREAD

**Issue by jacsonrbinf** [antonio-emilio/projeto_ed1#7]
@antonio-emilio e @melyssamariana,
Excelente trabalho, vocês concluíram o trabalho?

**Comment by antonio-emilio** [comment]
Boa tarde professor!
Acredito que sim, estivemos procurando algumas funcionalidades mas creio que o que tínhamos em mente foi feito.

**Comment by melyssamariana** [comment]
Boa tarde, procuramos mais funcionalidades com outras pessoas da empresa, e querem implementar o sistema de endereçamento sim, e não achamos mais alguma implementação.

**Comment by jacsonrbinf** [comment]
Boa tarde! Amanhã na aula vocês podem fazer a apresentação final. Obrigado!
